server:
  port: 8080

spring:
 servlet:
  multipart:
   enabled: true
   max-file-size: 500MB
   max-request-size: 500MB
 thymeleaf:
  cache: false
  check-template-location: true
  content-type: text/html
  encoding: UTF-8
  mode: HTML5
  prefix: classpath:/
  suffix: .html


filepath: D:/file/
wslog_commond: tail -f /root/tke.log


harbor:
 login_address: http://mmzwwwdocker.digitalgd.com:31104
 username: admin
 password: Harbor
 project: tsf_100000080
